### ISSUE TITLE
Examples interrupt & customdisplay are the same

### ISSUE THREAD

**Issue by fenollp** [superhawk610/bar#1]
```
∀ diff -q customdisplay/main.go interrupt/main.go; echo $?
0
```

Anyway, this is the only progress bar library in Golang that I've found that allows one to build an `apt`-like progress display (scrolling text above a progress bar)! Thanks to `.Interruptf(...)` & thank you!

**Comment by superhawk610** [comment]
Thanks! That was my exact use-case as well, glad to help.
