### ISSUE TITLE
allow displaying `0` ETA once bar reaches 100% completion

### ISSUE THREAD

**Issue by brendensoares** [superhawk610/bar#2]
https://github.com/superhawk610/bar/blob/4fbf44d086fd7d4a5ca0dce2abdbb7508343479e/tokens.go#L179

I'd expect 100% bar completion to show `0s` not an empty value.

For example, the format `:bar :eta remaining` currently renders `(████████████████████) remaining`.

**Comment by superhawk610** [comment]
My original intention with having `:eta` return an empty string when it reaches 0 is that the ETA would disappear once it's no longer needed:

```
(█████████████████   ) 10s
(███████████████████ ) 5s
(████████████████████)
```

I definitely could see wanting it to remain visible, and as I'm typing this out I think I've convinced myself that it's probably best to just have it display `0s` when it runs out.
